### ISSUE TITLE
Unable to see jellyfin contents

### ISSUE THREAD

**Issue by sdbabhishek** [patrickkfkan/volumio-jellyfin#2]
Hello patrickkfkan,
Thank you for the work.

Yesterday I got to know about jellyfin plugin and installed it over volumio ( version - 2.917).
I have a  local jellyfin media server running over docker.

Music cast from jellyfin web interface works fine.

I'm not able to find any contents of my jellyfin server, inside volumio_jellyfin.
I have added screen shot for your reference. Let me know, if this is under development or any issue from my end ?

Thanks 😊
Abhishek

![IMG_20211027_050459](https://user-images.githubusercontent.com/37470549/138975892-be30288c-bba5-4b3b-9e94-f2097e4a9dd9.jpg)
![IMG_20211027_050531](https://user-images.githubusercontent.com/37470549/138975899-74b4eb14-6c3f-410a-b3b3-9027a4edfb02.jpg)

**Comment by Malinskiy** [comment]
Hey @patrickkfkan, 
One possible cause of this problem is the lack of URL sanitization:

```
ConnectionManager response status: 404, url: https://jellyfin.xxx.yyy.com//system/info/public
```

The problem here is the URL of the host the is ending with an additional `/` since the path routes. It might be easier for users to input URL without this knowledge and the code to sanitize the URL on persisting it.

Cheers
