### ISSUE TITLE
Add to playlist not working from playback view

### ISSUE THREAD

**Issue by zebhlindqvist** [patrickkfkan/volumio-jellyfin#3]
Add to playlist does not work from the playback view.
When trying to add to playlist from the playback view i noticed a popup that says:
_http://192.168.176.233:8096/Audio/020dc83739b6cbf322b779b2e0bce178/stream.mp3?Static=true&MediaSourceId=020dc83739b6cbf322b779b2e0bce178&Tag=14e8ee5e01fe719d0d2e6b6ce39dca0f to playlist Test_

Screenshot:
![Jellyfin - Not working](https://user-images.githubusercontent.com/20443754/144795935-4e3afa00-ea3a-4166-a655-24947667ce2a.png)

Adding to playlist works from the Jellyfin view.
When doing so the popup says:
_jellyfin/c542b65c2d894b15b589b402818bb627/library@parentId=7e64e319657a9516ec78490da03edccb/songs@parentId=7e64e319657a9516ec78490da03edccb/song@songId=020dc83739b6cbf322b779b2e0bce178 to playlist Test_

Screenshot: 
![Jellyfin - Working](https://user-images.githubusercontent.com/20443754/144795971-a52316b0-6bb7-4093-9aaa-26c9e3b3d865.png)
  
Volumio v3.163
Jellyfin v0.1.4

**Comment by patrickkfkan** [comment]
I should be able to fix this. Will provide in next update.

**Comment by patrickkfkan** [comment]
I have fixed this issue and pushed an update to Volumio 3 plugin store. But I think you would have to wait before you can actually update it (and restart Volumio after updating). Right now I can see the Update button available but it still downloads the previous version...

I have also removed the enhanced titles when you have Manifest UI enabled, because these titles mess up the UI badly (no workaround I can think of). No big deal - you just lose the icons and the breadcrumbs at the top...

**Comment by patrickkfkan** [comment]
Closing this as resolved in version 0.1.5
